import keyMirror from 'keymirror'

export default keyMirror({
  GET_POOL_FEE: null,
  GET_POOL_PARAMS: null,
  GET_POOL_TOKEN_PARAMS: null,
  BIND_TOKEN_REQUEST: null,
  BIND_TOKEN_SUCCESS: null,
  BIND_TOKEN_FAILURE: null,
  SET_TOKEN_PARAMS_REQUEST: null,
  SET_TOKEN_PARAMS_SUCCESS: null,
  SET_TOKEN_PARAMS_FAILURE: null,
  SET_POOL_PARAMS_SUCCESS: null,
  SET_POOL_PARAMS_FAILURE: null,
  SWAP_EXACT_AMOUNT_IN_REQUEST: null,
  SWAP_EXACT_AMOUNT_IN_SUCCESS: null,
  SWAP_EXACT_AMOUNT_IN_FAILURE: null,
  GET_KNOWN_POOLS_REQUEST: null,
  GET_KNOWN_POOLS_SUCCESS: null,
  GET_KNOWN_POOLS_FAILURE: null,
  SET_PROVIDER: null
})
